In [2]:
import numpy as np

In [3]:
benimdizim = np.arange(0,15)

In [4]:
benimdizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimdizim[7]

7

In [6]:
benimdizim[3:5]

array([3, 4])

In [7]:
benimdizim[2:19]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
benimdizim[5:12]

array([ 5,  6,  7,  8,  9, 10, 11])

In [9]:
benimdizim[3:5] = -5
benimdizim

array([ 0,  1,  2, -5, -5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
baskadizi = np.arange(0,20)

In [11]:
baskadizi[4:9]

array([4, 5, 6, 7, 8])

In [12]:
slicingdizi = baskadizi[4:9]


In [23]:
baskadizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
slicingdizi


array([4, 5, 6, 7, 8])

In [14]:
slicingdizi[:] = 300

In [15]:
baskadizi #numpy da yapılan local değişiklikler dizinin tamamını da etkiler

array([  0,   1,   2,   3, 300, 300, 300, 300, 300,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [16]:
examplearray = np.arange(0,24)

In [17]:
examplearray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
examplearraycopy = examplearray.copy()


In [19]:
examplearraycopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
examplearraycopy[4:12]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
examplearraycopyslicing = examplearraycopy[4:10]

In [23]:
examplearraycopyslicing[:] = 200

In [24]:
examplearray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
examplearraycopy # numpy da eğer bir dizi üzerinde çalışıp dizinin orijinal hali kalsın istiyorsak copy ile çağırıp işlem yaparak yeni dizi oluşturmalıyız

array([  0,   1,   2,   3, 200, 200, 200, 200, 200, 200,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# matrix

In [28]:
benimlistem = [[1,2,3,],[2,3,5],[5,6,7]]

In [29]:
matrixdizim = np.array(benimlistem)

In [30]:
matrixdizim

array([[1, 2, 3],
       [2, 3, 5],
       [5, 6, 7]])

In [31]:
matrixdizim[0]


array([1, 2, 3])

In [32]:
matrixdizim[1][2]

5

In [33]:
matrixdizim[1,2]

5

In [34]:
matrixdizim[1,2]

5

In [35]:
matrixdizim[1: ,2]

array([5, 7])

In [36]:
matrixdizim[0:,2]

array([3, 5, 7])

In [37]:
matrixdizim

array([[1, 2, 3],
       [2, 3, 5],
       [5, 6, 7]])

In [42]:
matrixdizim[1:3,:2]

array([[2, 3],
       [5, 6]])

In [52]:
newlist = [[0,1,2,3,4],[7,8,9,10,11],[10,23,1,2,3],[1,2,3,4,5]]


In [53]:
newmatrix = np.array(newlist)


In [54]:
newmatrix

array([[ 0,  1,  2,  3,  4],
       [ 7,  8,  9, 10, 11],
       [10, 23,  1,  2,  3],
       [ 1,  2,  3,  4,  5]])

In [57]:
newmatrix[[1,3]]

array([[ 7,  8,  9, 10, 11],
       [ 1,  2,  3,  4,  5]])

In [58]:
newmatrix[[0,2,3]]

array([[ 0,  1,  2,  3,  4],
       [10, 23,  1,  2,  3],
       [ 1,  2,  3,  4,  5]])

In [59]:
newmatrix[[3,2]]

array([[ 1,  2,  3,  4,  5],
       [10, 23,  1,  2,  3]])