In [1]:
import numpy as np


# numpy array 

In [3]:
benimlistem = [20,30,40]

In [4]:
type(benimlistem)

list

In [5]:
np.array(benimlistem)

array([20, 30, 40])

In [6]:
matrixlistesi = [[10,20,30],[30,40,50],[60,70,80]]

In [7]:
type(matrixlistesi)

list

In [8]:
np.array(matrixlistesi)

array([[10, 20, 30],
       [30, 40, 50],
       [60, 70, 80]])

# numpy methodları 

# arange methodu

In [10]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,19,3)

array([ 0,  3,  6,  9, 12, 15, 18])

# zeros

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((6))

array([1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# linspace

In [19]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [20]:
np.linspace(0,100,200)

array([  0.        ,   0.50251256,   1.00502513,   1.50753769,
         2.01005025,   2.51256281,   3.01507538,   3.51758794,
         4.0201005 ,   4.52261307,   5.02512563,   5.52763819,
         6.03015075,   6.53266332,   7.03517588,   7.53768844,
         8.04020101,   8.54271357,   9.04522613,   9.54773869,
        10.05025126,  10.55276382,  11.05527638,  11.55778894,
        12.06030151,  12.56281407,  13.06532663,  13.5678392 ,
        14.07035176,  14.57286432,  15.07537688,  15.57788945,
        16.08040201,  16.58291457,  17.08542714,  17.5879397 ,
        18.09045226,  18.59296482,  19.09547739,  19.59798995,
        20.10050251,  20.60301508,  21.10552764,  21.6080402 ,
        22.11055276,  22.61306533,  23.11557789,  23.61809045,
        24.12060302,  24.62311558,  25.12562814,  25.6281407 ,
        26.13065327,  26.63316583,  27.13567839,  27.63819095,
        28.14070352,  28.64321608,  29.14572864,  29.64824121,
        30.15075377,  30.65326633,  31.15577889,  31.65

# eye

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# random 

In [22]:
np.random.randn(8)

array([ 1.12612739, -1.26253075,  0.0753273 ,  1.01438009, -0.01280054,
       -0.16918274,  0.34317991, -0.27873221])

In [23]:
np.random.randn(4,4)

array([[-0.88713876, -1.19955638, -0.06943923,  0.30344627],
       [ 0.02886485,  0.9668792 , -0.37916546,  0.64380156],
       [ 0.35760642, -0.24298599, -1.24503748, -1.16997962],
       [-1.21057265, -0.96403922,  0.22021382, -0.40961217]])

In [26]:
np.random.randint(1,20)

12

In [28]:
np.random.randint(1,10)


8

In [ ]:
np.random.randint()



In [29]:
benimdizim = np.arange(30)
benimdizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
benimrandomdizim = np.random.randint(0,100,30)
benimrandomdizim

array([ 8,  3, 46, 33, 17, 75, 80, 31, 85, 25, 71, 39, 70, 97, 38, 30, 21,
       53, 29, 20, 76, 32, 64, 73, 84, 66, 37, 23, 42, 44])

# numpy dizi methodlari

In [31]:
benimdizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
benimdizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [33]:
benimdizim.max()

29

In [34]:
benimrandomdizim.max()

97

In [35]:
benimdizim.argmax()

29

In [36]:
benimrandomdizim.argmin()

1

In [37]:
benimdizim.argmin()

0

In [38]:
benimdizim.shape

(30,)

In [39]:
reshapebenimdizim = benimdizim.reshape(5,6)
reshapebenimdizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [40]:
reshapebenimdizim.shape #güncel dizimin hangi şekle sahip olduğunu bulmak için kullanılır

(5, 6)